# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


#MaxClientes: Default value that indicates the number of clients to create
MaxClientes = 2

#Comprobamos que la memoria del propietario es suficiente para ejecutar el proyecto
#Con los parámetros dados (ram clientes y ram servidor)
#Se le resta 512 de ram al propietario para tener un margen de seguridad
RamPropietary = Integer((%x( grep -i memtotal /proc/meminfo | tr -dc '0-9' ))-512)/1024
RamExecution=2048+(512*MaxClientes)

if RamExecution >=RamPropietary
    puts ('Error: your RAM is '+String(RamPropietary)+ ' and the one you need to run is ' +String(RamExecution))
    puts ('We advise you to decrease the number of clients, or decrease the number of clients')
    abort("Try again with the above. Bye")
end


#Vagrant
Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "grep -i memtotal /proc/meminfo"
end


Vagrant.configure(2) do |config|



    config.vm.box = "centos/7"

    config.vm.define "sl1" do |sl1|
                                            #la ip debería estar en el rango 192.168.100.0, pero me daba conflicto con el propietario (Se hablo por mail)
        sl1.vm.network "private_network", ip: "192.168.200.50", auto_config: true

        sl1.vm.provider "virtualbox" do |v|
            v.name = "ipa-sl1"
            v.memory = 2048
            v.cpus = 2
            v.gui = false
        end

        sl1.vm.provision "network-config", type: "shell" do |s|
	     # Configuración de red del servidor
	    s.path = "./scripts/network-config.sh"
        #NameHost,Iphost,Ipdns
        s.args=["ipa-sl1","192.168.200.50","8.8.8.8"]
        end

        sl1.vm.provision "ipa-server-install", type: "shell" do |s|
	    # Instalación del servidor IPA
        s.path = "./scripts/ipa-server-install.sh"
	    s.args=["ipa-sl1"]
        end

        sl1.vm.provision "ipa-server-addusers", type: "shell" do |s|
	    # Añadir usuarios al servidor IPA 
        s.path = "./scripts/ipa-server-addusers.sh"
	    s.args=["usuarios.csv"]
        end

    end


  ListClients=1..MaxClientes
  (ListClients).each do |i|
	

    config.vm.define "cl#{i}" do |cli|

    	cli.vm.network "private_network", ip: "192.168.200.5#{i}", auto_config: true

    	cli.vm.provider "virtualbox" do |v|
    		v.name = "ipa-cl#{i}"
    		v.memory = 512
    		v.cpus = 1
    		v.gui = false
   	end

	cli.vm.provision "network-config", type: "shell" do |s|
		# Configuración de red del cliente 
		s.path = "./scripts/network-config.sh"
		s.args=["ipa-cl#{i}","192.168.200.5#{i}","192.168.200.50"]
	       end
	cli.vm.provision "ipa-client-install", type: "shell" do |s|
		# Instalación del cliente IPA
		s.path = "./scripts/ipa-client-install.sh"
		s.args=["#{i}"]
	       end
     end
  end
end
