# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

    config.vm.box = "centos/7"

    config.vm.define "sl1" do |sl1|
                                            #la ip debería estar en el rango 192.168.100.0
        sl1.vm.network "private_network", ip: "192.168.200.50", auto_config: true

        sl1.vm.provider "virtualbox" do |v|
            v.name = "ipa-sl1"
            v.memory = 2049
            v.cpus = 2
            v.gui = false
        end

        sl1.vm.provision "network-config", type: "shell" do |s|
	     # Configuración de red del servidor
	    s.path = "./scripts/network-config.sh"
        s.args=["ipa-sl1","192.168.200.50","8.8.8.8"]
        end

        sl1.vm.provision "ipa-server-install", type: "shell" do |s|
	    # Instalación del servidor IPA
        s.path = "./scripts/ipa-server-install.sh"
	    s.args=["ipa-sl1"]
        end

        sl1.vm.provision "ipa-server-addusers", type: "shell" do |s|
	    # Añadir usuarios al servidor IPA 
        s.path = "./scripts/ipa-server-addusers.sh"
	    s.args=["usuarios.csv"]
        end

    end

    config.vm.define "cl1" do |cli|
    	cli.vm.network "private_network", ip: "192.168.200.51", auto_config: true

    	cli.vm.provider "virtualbox" do |v|
    		v.name = "ipa-cl1"
    		v.memory = 512
    		v.cpus = 1
    		v.gui = false
   	end

	cli.vm.provision "network-config", type: "shell" do |s|
	# Configuración de red del cliente 
	s.path = "./scripts/network-config.sh"
        s.args=["ipa-cl1","192.168.200.51","192.168.200.50"]
       end
	cli.vm.provision "ipa-client-install", type: "shell" do |s|
	# Instalación del cliente IPA
	s.path = "./scripts/ipa-client-install.sh"
       end

    end
end
